--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/harman/wallpapers/Cat.jpg"

-- Special
background="#020202"
foreground="#eaeaea"
cursor="#eaeaea"

-- Colors
color0="#020202"
color1="#9D9DA0"
color2="#B1B1B1"
color3="#C2C3BF"
color4="#D1D1D1"
color5="#DFE0DE"
color6="#E1E1DE"
color7="#eaeaea"
color8="#a3a3a3"
color9="#9D9DA0"
color10="#B1B1B1"
color11="#C2C3BF"
color12="#D1D1D1"
color13="#DFE0DE"
color14="#E1E1DE"
color15="#eaeaea"
