# Shell variables
# Generated by 'wal'
wallpaper='/home/harman/wallpapers/Cat.jpg'

# Special
background='#020202'
foreground='#eaeaea'
cursor='#eaeaea'

# Colors
color0='#020202'
color1='#9D9DA0'
color2='#B1B1B1'
color3='#C2C3BF'
color4='#D1D1D1'
color5='#DFE0DE'
color6='#E1E1DE'
color7='#eaeaea'
color8='#a3a3a3'
color9='#9D9DA0'
color10='#B1B1B1'
color11='#C2C3BF'
color12='#D1D1D1'
color13='#DFE0DE'
color14='#E1E1DE'
color15='#eaeaea'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
