#!/bin/bash
source ~/.cache/wal/colors.sh

cat > ~/.config/mpv/mpv-pywal.conf << MPV
osd-color='${color15}'
osd-border-color='${color0}'
sub-color='${color15}'
sub-border-color='${color0}'
MPV

grep -q "include=.*mpv-pywal.conf" ~/.config/mpv/mpv.conf || echo "include=~/.config/mpv/mpv-pywal.conf" >> ~/.config/mpv/mpv.conf
